name: Practice full stack CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-Fullstack-App:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code from Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Frontend dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Cache Frontend node_modules
        uses: actions/cache@v3
        with:
          path: |
            ./Frontend/node_modules
          key: frontend-${{ hashFiles('Frontend/package-lock.json') }}

      - name: Build Frontend
        working-directory: ./Frontend
        run: npm run build

      - name: Install Backend dependencies
        working-directory: ./Backend
        run: npm install

      - name: Cache Backend node_modules
        uses: actions/cache@v3
        with:
          path: |
            ./Backend/node_modules
          key: backend-${{ hashFiles('Backend/package-lock.json') }}